### ISSUE TITLE
Support new endpoints

### ISSUE THREAD

**Issue by citizenfish** [xmpli/locus-qgis#13]
These need adding (and testing)

```
/search/{category}/{search_text}/{limit}/{offset}

/pointsearch/{location}/{location_distance}/{category}/{search_text}/{limit}/{offset}
(location is in EWKT format, distance in metres)

/refsearch/{reference}/{category}/{limit}/{offset}
(reference alphanumeric)

/address_search/{address}/{limit}/{offset}
(address is a freeform addresss
```

limit default 100, offset default 0

**Comment by MidgetJake** [comment]
The only issue with these at the moment is that if the `{search_text}` is empty then it will use the limit as the search text.

To counteract this, the search text will default to just a single space. If there is a better way or something else that should be done I can reopen this.
